
name: Markdownlint Action

on:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.json'
      - '.markdownlintignore'
      - '.github/workflows/markdownlint.yml'

permissions:
  contents: read

jobs:
  build:
    name: Markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Markdownlint
        uses: nosborn/github-action-markdown-cli@508d6cefd8f0cc99eab5d2d4685b1d5f470042c1 # v3.5.0
        with:
          files: .
          config_file: ".markdownlint.json"
