name: Spellcheck Action

on:
  # Enabling manual test
  # REF: https://stackoverflow.com/questions/58933155/manual-workflow-triggers-in-github-actions
  workflow_dispatch:
  push:
    paths:
      - '**/*.md'
      - 'spellcheck.yaml'
      - 'wordlist.txt'
      - '.github/workflows/spelling_action.yml'

permissions:
  contents: read

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Spellcheck
        uses: rojopolis/spellcheck-github-actions@e619e00ca22f01ade9d73048dcd6518bedc552f2 # v0.63.0
        with:
          source_files: README.md CHANGELOG.md
          task_name: Markdown
          output_file: spellcheck-output.txt

      - name: Archive spellcheck output
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: '!cancelled()'
        with:
          name: Spellcheck artifact
          path: spellcheck-output.txt
