name: Spellcheck Action

on:
  # Enabling manual test
  # REF: https://stackoverflow.com/questions/58933155/manual-workflow-triggers-in-github-actions
  workflow_dispatch:
  push:

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:

      # The checkout step
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v4

      - uses: rojopolis/spellcheck-github-actions@e3cd8e9aec4587ec73bc0e60745aafd45c37aa2e # ratchet:rojopolis/spellcheck-github-actions@v0
        name: Spellcheck
        with:
          source_files: README.md CHANGELOG.md
          task_name: Markdown
          output_file: spellcheck-output.txt

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # ratchet:actions/upload-artifact@v4
        if: '!cancelled()'
        name: Archive spellcheck output
        with:
          name: Spellcheck artifact
          path: spellcheck-output.txt
